// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAmI3r9j1h1H-wynJCjo7R4R90jUK0Gw8',
    appId: '1:263595612990:web:4770af369c6bca018eea6f',
    messagingSenderId: '263595612990',
    projectId: 'mrkapp-d2cf7',
    authDomain: 'mrkapp-d2cf7.firebaseapp.com',
    storageBucket: 'mrkapp-d2cf7.firebasestorage.app',
    measurementId: 'G-CJB431T1Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqgFCofuWBNHgX83l2lvjvu01sJGaaVEI',
    appId: '1:263595612990:android:cbc7c3273ccae8328eea6f',
    messagingSenderId: '263595612990',
    projectId: 'mrkapp-d2cf7',
    storageBucket: 'mrkapp-d2cf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS5qFc0r7FbHxHguxkoFKrp9Sil13I-f4',
    appId: '1:263595612990:ios:229a750ca34d02088eea6f',
    messagingSenderId: '263595612990',
    projectId: 'mrkapp-d2cf7',
    storageBucket: 'mrkapp-d2cf7.firebasestorage.app',
    iosBundleId: 'com.example.mrk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS5qFc0r7FbHxHguxkoFKrp9Sil13I-f4',
    appId: '1:263595612990:ios:229a750ca34d02088eea6f',
    messagingSenderId: '263595612990',
    projectId: 'mrkapp-d2cf7',
    storageBucket: 'mrkapp-d2cf7.firebasestorage.app',
    iosBundleId: 'com.example.mrk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAmI3r9j1h1H-wynJCjo7R4R90jUK0Gw8',
    appId: '1:263595612990:web:791303a36f11ce858eea6f',
    messagingSenderId: '263595612990',
    projectId: 'mrkapp-d2cf7',
    authDomain: 'mrkapp-d2cf7.firebaseapp.com',
    storageBucket: 'mrkapp-d2cf7.firebasestorage.app',
    measurementId: 'G-LYT77XSJRY',
  );
}
