import 'package:flutter/material.dart';
import '../models/formationt.dart';
import '../services/formation_service.dart';
import '../services/auth_service.dart';
import '../theme/app_theme.dart';
import '../widgets/aureus_background.dart';

class AdminFormationsScreen extends StatefulWidget {
  const AdminFormationsScreen({super.key});

  @override
  State<AdminFormationsScreen> createState() => _AdminFormationsScreenState();
}

class _AdminFormationsScreenState extends State<AdminFormationsScreen> {
  void _showAddDialog() {
    final titleController = TextEditingController();
    final descController = TextEditingController();
    final imageController = TextEditingController();
    final priceController = TextEditingController();
    bool isLoading = false;

    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => StatefulBuilder(
        builder: (context, setStateDialog) {
          return Dialog(
            backgroundColor: Colors.transparent,
            insetPadding: const EdgeInsets.all(20),
            child: Container(
              padding: const EdgeInsets.all(24),
              decoration: AppTheme.glassDecoration(borderRadiusVal: 24).copyWith(
                color: AppTheme.primaryColor.withValues(alpha: 0.9),
              ),
              child: SingleChildScrollView(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text('Ajouter une Formation', style: TextStyle(color: AppTheme.secondaryColor, fontSize: 20, fontWeight: FontWeight.bold)),
                    const SizedBox(height: 20),
                    _buildTextField(titleController, 'Titre de la formation', Icons.title),
                    const SizedBox(height: 12),
                    _buildTextField(descController, 'Description', Icons.description, maxLines: 3),
                    const SizedBox(height: 12),
                    _buildTextField(imageController, 'URL de l\'image (unsplash...)', Icons.image),
                    const SizedBox(height: 12),
                    _buildTextField(priceController, 'Prix (FCFA)', Icons.attach_money, isNumber: true),
                    const SizedBox(height: 24),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.end,
                      children: [
                        TextButton(
                          onPressed: isLoading ? null : () => Navigator.pop(context),
                          child: const Text('Annuler', style: TextStyle(color: Colors.white54)),
                        ),
                        const SizedBox(width: 12),
                        ElevatedButton(
                          style: ElevatedButton.styleFrom(
                            backgroundColor: AppTheme.secondaryColor,
                            foregroundColor: AppTheme.primaryColor,
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                          ),
                          onPressed: isLoading
                              ? null
                              : () async {
                                  if (titleController.text.isEmpty || priceController.text.isEmpty) return;
                                  setStateDialog(() => isLoading = true);
                                  
                                  try {
                                    final newFormation = Formation(
                                      id: '', // Generated by Firestore
                                      title: titleController.text.trim(),
                                      description: descController.text.trim(),
                                      imageUrl: imageController.text.trim().isNotEmpty 
                                          ? imageController.text.trim() 
                                          : 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=400&fit=crop',
                                      price: double.tryParse(priceController.text.trim()) ?? 0.0,
                                    );
                                    await FormationService.addFormation(newFormation);
                                    if (context.mounted) Navigator.pop(context);
                                  } catch (e) {
                                    setStateDialog(() => isLoading = false);
                                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Erreur: $e')));
                                  }
                                },
                          child: isLoading 
                              ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2, color: AppTheme.primaryColor))
                              : const Text('Créer', style: TextStyle(fontWeight: FontWeight.bold)),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          );
        }
      ),
    );
  }

  Widget _buildTextField(TextEditingController controller, String hint, IconData icon, {int maxLines = 1, bool isNumber = false}) {
    return Container(
      decoration: AppTheme.glassDecoration(borderRadiusVal: 12),
      child: TextField(
        controller: controller,
        style: const TextStyle(color: Colors.white),
        maxLines: maxLines,
        keyboardType: isNumber ? TextInputType.number : TextInputType.text,
        decoration: InputDecoration(
          hintText: hint,
          hintStyle: const TextStyle(color: Colors.white30),
          prefixIcon: Icon(icon, color: AppTheme.secondaryColor, size: 20),
          border: InputBorder.none,
          contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return AureusBackground(
      child: Scaffold(
        backgroundColor: Colors.transparent,
        appBar: AppBar(
          title: const Text('Espace Administrateur'),
          centerTitle: true,
          backgroundColor: Colors.transparent,
          elevation: 0,
          foregroundColor: Colors.white,
          actions: [
            IconButton(
              tooltip: 'Deconnexion',
              onPressed: () => AuthService.instance.signOut(),
              icon: const Icon(Icons.logout),
            ),
          ],
        ),
        floatingActionButton: Container(
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            gradient: AppTheme.goldGradient,
            boxShadow: [
              BoxShadow(color: AppTheme.secondaryColor.withValues(alpha: 0.4), blurRadius: 15, offset: const Offset(0, 5)),
            ],
          ),
          child: FloatingActionButton(
            backgroundColor: Colors.transparent,
            elevation: 0,
            onPressed: _showAddDialog,
            child: const Icon(Icons.add, color: AppTheme.primaryColor, size: 32),
          ),
        ),
        body: StreamBuilder<List<Formation>>(
          stream: FormationService.watchFormations(),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return const Center(child: CircularProgressIndicator(color: AppTheme.secondaryColor));
            }
            if (snapshot.hasError) {
              return Center(child: Text('Erreur: ${snapshot.error}', style: const TextStyle(color: Colors.red)));
            }
            
            final formations = snapshot.data ?? [];
            if (formations.isEmpty) {
              return const Center(child: Text('Aucune formation codée.', style: TextStyle(color: Colors.white54)));
            }

            return ListView.builder(
              padding: const EdgeInsets.all(16),
              itemCount: formations.length,
              itemBuilder: (context, index) {
                final form = formations[index];
                return Container(
                  margin: const EdgeInsets.only(bottom: 12),
                  decoration: AppTheme.glassDecoration(borderRadiusVal: 16).copyWith(
                    color: AppTheme.surfaceColor.withValues(alpha: 0.4),
                  ),
                  child: ListTile(
                    contentPadding: const EdgeInsets.all(12),
                    leading: ClipRRect(
                      borderRadius: BorderRadius.circular(8),
                      child: Image.network(form.imageUrl, width: 60, height: 60, fit: BoxFit.cover,
                        errorBuilder: (_,__,___) => Container(width: 60, height: 60, color: Colors.grey, child: const Icon(Icons.error)),
                      ),
                    ),
                    title: Text(form.title, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold), maxLines: 1, overflow: TextOverflow.ellipsis),
                    subtitle: Text('${form.price} FCFA', style: const TextStyle(color: AppTheme.secondaryColor, fontWeight: FontWeight.w600)),
                    trailing: IconButton(
                      icon: const Icon(Icons.delete_outline, color: Colors.redAccent),
                      onPressed: () async {
                        final confirm = await showDialog<bool>(
                          context: context,
                          builder: (context) => AlertDialog(
                            backgroundColor: AppTheme.surfaceColor,
                            title: const Text('Supprimer ?', style: TextStyle(color: Colors.white)),
                            content: const Text('Voulez-vous vraiment supprimer cette formation ?', style: TextStyle(color: Colors.white70)),
                            actions: [
                              TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Annuler')),
                              TextButton(onPressed: () => Navigator.pop(context, true), child: const Text('Supprimer', style: TextStyle(color: Colors.red))),
                            ],
                          ),
                        );
                        if (confirm == true) {
                          await FormationService.deleteFormation(form.id);
                        }
                      },
                    ),
                  ),
                );
              },
            );
          },
        ),
      ),
    );
  }
}
